<div class="wrap">
    <label for="hcc_api_token">Hetzner Online Cloud API Token</label>
    <input type="text" id="hcc_token" value="<?php echo get_option( baekerIT_Hetzner_Cloud_Control::API_TOKEN ) ?>"/>
    <button type="button" onclick="saveToken()">API Token speichern</button>
    <script>
      function saveToken() {
        var token = jQuery('#hcc_token').val();
        jQuery.ajax({
           method: 'POST',
           url: '<?php echo admin_url('admin-ajax.php'); ?>',
           data: {
               action: 'hcc_saveToken',
               token: token,
           },
            success: function(response){
               alert(response);
            }
        });
      }
    </script>
</div>