<div class="wrap">
    <button class="btn btn-primary" role="button" data-toggle="collapse" data-target="#createServer" aria-expanded="false"
            aria-controls="createServer">
        Create a new Server
    </button>
    <div class="collapse" id="createServer">
        <div class="well">
            <div class="col-md-4">
                <label for="createServerName">New Server Name</label>
                <input type="text" id="createServerName" class="form-control"/>
            </div>
            <div class="col-md-4">
                <select id="createServerType" class="">
                    <option selected disabled>Select a Server Type</option>
					<?php
                        foreach (Hetzner_Cloud_Control_Remote_API::getAllServerTypes()->server_types as $type):
                            ?>
                            <option value="<?php echo $type->name ?>"><?php echo $type->description ?></option>
                        <?php
                        endforeach;
					?>
                </select>
            </div>
            <div class="col-md-4">
                <select id="createServerImage" class="">
                    <option selected disabled>Select a Server OS Image</option>
					<?php
                        foreach (Hetzner_Cloud_Control_Remote_API::getAllImages()->images as $image):
                            ?>
                            <option value="<?php echo $image->name ?>"><?php echo $image->description ?></option>
                        <?php
                        endforeach;
                        ?>
                </select>
            </div>
            <div class="col-md-12">
                <button type="button" class="btn btn-success" onclick="createServer()">Create your new Server</button>
            </div>
            <script>
              function createServer() {
                var name = jQuery('#createServerName').val();
                var type = jQuery('#createServerType').val();
                var image = jQuery('#createServerImage').val();
                jQuery.ajax({
                   url: '<?php echo admin_url('admin-ajax.php') ?>',
                   method: 'POST',
                   data: {
                       action: 'createNewServer',
                       name: name,
                       type: type,
                       image: image
                   },
                   success: function(response){
                       alert(response);
                       jQuery('#createServerName').val('');
                       jQuery('#createServerType').val('');
                       jQuery('#createServerImage').val('');
                   }
                });
              }
            </script>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Status</th>
            <th>Erstellt</th>
            <th>IPv4</th>
            <th>IPv6</th>
        </tr>
        </thead>
        <tbody>
		<?php
		foreach ( Hetzner_Cloud_Control_Remote_API::getAllServers()->servers as $server ):
			?>
            <tr id="server_<?php echo $server->id ?>">
                <td><?php
					echo $server->id
					?></td>
                <td>
                    <input type="text" value="<?php echo $server->name ?>" id="<?php echo $server->id?>_name"></td>
                <td><?php
					echo $server->status
					?></td>
                <td><?php
					echo $server->created
					?></td>
                <td><?php
					if ( ! $server->public_net->ipv4->blocked ):
						echo '<span style="color:green">';
						echo $server->public_net->ipv4->ip;
					else:
						echo '<span style="color:red">';
					endif;
					?>
                    </span></td>
                <td><?php
					if ( ! $server->public_net->ipv6->blocked ):
						echo '<span style="color:green">';
						echo $server->public_net->ipv6->ip;
					else:
						echo '<span style="color:red">';
					endif;
					?>
                    </span></td>
                <td>
                    <button type="button" class="btn btn-warning" onclick="changeName(<?php echo $server->id ?>)">Aktualisieren</button>
                </td>
                <td>
                    <button type="button" class="btn btn-danger" onclick="deleteServer(<?php echo $server->id ?>)">Löschen</button>
                </td>
            </tr>
		<?php
		endforeach;
		?>
        </tbody>
        <script>
            function changeName(id){
                var name = jQuery('#'+id+'_name').val();
                jQuery.ajax({
                    url: '<?php echo admin_url('admin-ajax.php') ?>',
                    method: 'POST',
                    data: {
                        action: 'hcc_changeName',
                        server_id: id,
                        name: name,
                    },
                    success: function(response){
                        jQuery('#server_'+id).setAttribute('style', 'background:yellow');
                    }
                })
            }

            function deleteServer(id){
                jQuery.ajax({
                    url: '<?php echo admin_url('admin-ajax.php') ?>',
                    method: 'POST',
                    data: {
                        action: 'hcc_deleteServer',
                        id: id
                    },
                    success: function(response){
                        jQuery('#server_'+id).setAttribute('style', 'background:red');
                    }
                })
            }
        </script>
    </table>
</div>